Downloads/tracks-2.3.0/config/routes.rb
Rails.application.routes.draw do
  mount Tolk::Engine => '/tolk', :as => 'tolk' if Rails.env=='development'

  root :to => 'todos#index'

  post 'mailgun/mime' => 'mailgun#mailgun'

  post 'login' => 'login#login'
  get 'login' => 'login#login'
  get 'login/check_expiry' => 'login#check_expiry'
  get 'logout' => 'login#logout'

  get "tickler" => "todos#list_deferred"
  get 'review' => "projects#review"
  get 'calendar' => "calendar#show"
  get 'done' => "stats#done", :as => 'done_overview'

  get 'search' => 'search#index'
  post 'search/results' => 'search#results', :via => 'post'

  get 'data' => "data#index"
  get 'data/csv_notes' => 'data#csv_notes'
  get 'data/yaml_export' => 'data#yaml_export'
  get 'data/xml_export' => 'data#xml_export'
  get 'data/csv_actions' => 'data#csv_actions'

  get 'integrations' => "integrations#index"
  get 'integrations/rest_api' => "integrations#rest_api", :as => 'rest_api_docs'
  post 'integrations/cloudmailin' => 'integrations#cloudmailin'
  get 'integrations/search_plugin' => "integrations#search_plugin", :as => 'search_plugin'
  get 'integrations/google_gadget.xml' => 'integrations#google_gadget', :as => 'google_gadget'

  get 'preferences' => "preferences#index"
  get 'preferences/render_date_format' => "preferences#render_date_format"

  get 'feeds' => "feedlist#index", :as => 'feeds'
  get 'feedlist/get_feeds_for_context' => 'feedlist#get_feeds_for_context'
  get 'feedlist/get_feeds_for_project' => 'feedlist#get_feeds_for_project'

  get 'stats' => 'stats#index'
  get 'stats/actions_done_last12months_data' => 'stats#actions_done_last12months_data'
  get 'stats/actions_done_last_years' => 'stats#actions_done_last_years'
  get 'stats/actions_done_lastyears_data' => 'stats#actions_done_lastyears_data'
  get 'stats/actions_done_last30days_data' => 'stats#actions_done_last30days_data'
  get 'stats/actions_completion_time_data' => 'stats#actions_completion_time_data'
  get 'stats/actions_running_time_data' => 'stats#actions_running_time_data'
  get 'stats/actions_visible_running_time_data' => 'stats#actions_visible_running_time_data'
  get 'stats/actions_open_per_week_data' => 'stats#actions_open_per_week_data'
  get 'stats/context_total_actions_data' => 'stats#context_total_actions_data'
  get 'stats/context_running_actions_data' => 'stats#context_running_actions_data'
  get 'stats/actions_day_of_week_all_data' => 'stats#actions_day_of_week_all_data'
  get 'stats/actions_day_of_week_30days_data' => 'stats#actions_day_of_week_30days_data'
  get 'stats/actions_time_of_day_all_data' => 'stats#actions_time_of_day_all_data'
  get 'stats/actions_time_of_day_30days_data' => 'stats#actions_time_of_day_30days_data'
  get 'stats/show_selected_actions_from_chart/:id' => 'stats#show_selected_actions_from_chart', :as => 'show_actions_from_chart'

  resources :contexts do
    member do
      get 'done_todos'
      get 'all_done_todos'
    end
    collection do
      post 'order'
      get 'done'
    end
    resources :todos
  end

  resources :projects do
    member do
      get 'done_todos'
      get 'all_done_todos'
      get 'set_reviewed'  # TODO: convert to PUT/POST
    end
    collection do
      get 'done'
      post 'order'
      post 'alphabetize'
      post 'actionize'
    end
    resources :todos
  end

  resources :todos do
    member do
      put 'toggle_check'
      put 'toggle_star'
      put 'defer'
      get 'show_notes'
      get 'convert_to_project' # TODO: convert to PUT/POST
      delete 'remove_predecessor' # TODO: convert to PUT/POST
      post 'change_context'
    end
    collection do
      get 'done'
      get 'all_done'
      post 'check_deferred'
      post 'filter_to_context'
      post 'filter_to_project'
      post 'add_predecessor'
    end
  end

  # match /todos/tag and put everything in :name, including extensions like .m and .txt. 
  # This means the controller action needs to parse the extension and set format/content type
  # Needed for /todos/tag/first.last.m to work
  get 'todos/tag/:name' => 'todos#tag', :as => :tag, :format => false, :name => /.*/
  
  get 'tags.autocomplete' => "todos#tags", :format => 'autocomplete'
  get 'todos/done/tag/:name' => "todos#done_tag", :as => :done_tag
  get 'todos/all_done/tag/:name' => "todos#all_done_tag", :as => :all_done_tag
  get 'auto_complete_for_predecessor' => 'todos#auto_complete_for_predecessor'
  get 'mobile' => 'todos#index', :format => 'm'
  get 'm' => 'todos#index', :format => 'm'

  resources :recurring_todos do
    member do
      put 'toggle_check'
      put 'toggle_star'
    end
    collection do
      get 'done'
    end
  end

  resources :users do
    member do
      get 'change_password'
      get 'change_auth_type'
      get 'complete'
      post 'update_password'
      post 'update_auth_type'
      post 'refresh_token'
    end
  end
  get 'signup' => "users#new"

  resources :notes
  resources :preferences

  resources :data do
    collection do
      get :import
      post :csv_map
      post :csv_import
    end
  end

end

Downloads/tracks-2.3.0/app/models/stats/actions.rb
module Stats
  class Actions

    SECONDS_PER_DAY = 86400;

    attr_reader :user
    def initialize(user)
      @user = user
    end

    def ttc
      @ttc ||= TimeToComplete.new(completed)
    end

    def done_last30days
      @done_last30days ||= done_since(one_month)
    end

    def done_last12months
      @done_last12months ||= done_since(one_year)
    end

    def created_last30days
      @sum_actions_created_last30days ||= new_since(one_month)
    end

    def created_last12months
      @sum_actions_created_last12months ||= new_since(one_year)
    end

    def completion_charts
      @completion_charts ||= %w{
     actions_done_last30days_data
     actions_done_last12months_data
     actions_completion_time_data
      }.map do |action|
        Stats::Chart.new(action)
      end
    end

    def timing_charts
      @timing_charts ||= %w{
      actions_visible_running_time_data
      actions_running_time_data
      actions_open_per_week_data
      actions_day_of_week_all_data
      actions_day_of_week_30days_data
      actions_time_of_day_all_data
      actions_time_of_day_30days_data
      }.map do |action|
        Stats::Chart.new(action)
      end
    end

    private

    def one_year
      @one_year ||= 12.months.ago.beginning_of_day
    end

    def one_month
      @one_month ||= 1.month.ago.beginning_of_day
    end

    def new_since(cutoff)
      user.todos.created_after(cutoff).count
    end

    def done_since(cutoff)
      user.todos.completed.completed_after(cutoff).count
    end

    def completed
      @completed ||= user.todos.completed.select("completed_at, created_at")
    end
  end
end

Downloads/tracks-2.3.0/app/models/stats/chart.rb
module Stats

  class Chart

    attr_reader :action, :height, :width
    def initialize(action, dimensions = {})
      @action = action
      @height = dimensions.fetch(:height) { 250 }
      @width = dimensions.fetch(:width) { 460 }
    end

    def dimensions
      "#{width}x#{height}"
    end

  end

end

Downloads/tracks-2.3.0/app/controllers/stats_controller.rb
class StatsController < ApplicationController

  SECONDS_PER_DAY = 86400;

  helper :todos, :projects, :recurring_todos
  append_before_filter :init, :except => :index

  def index
    @page_title = t('stats.index_title')
    @hidden_contexts = current_user.contexts.hidden
    @stats = Stats::UserStats.new(current_user)
  end

  def actions_done_last12months_data
    # get actions created and completed in the past 12+3 months. +3 for running
    # - outermost set of entries needed for these calculations
    actions_last12months = current_user.todos.created_or_completed_after(@cut_off_year_plus3).select("completed_at,created_at")

    # convert to array and fill in non-existing months
    @actions_done_last12months_array = put_events_into_month_buckets(actions_last12months, 13, :completed_at)
    @actions_created_last12months_array = put_events_into_month_buckets(actions_last12months, 13, :created_at)

    # find max for graph in both arrays
    @max = (@actions_done_last12months_array + @actions_created_last12months_array).max

    # find running avg
    done_in_last_15_months = put_events_into_month_buckets(actions_last12months, 16, :completed_at)
    created_in_last_15_months = put_events_into_month_buckets(actions_last12months, 16, :created_at)

    @actions_done_avg_last12months_array = compute_running_avg_array(done_in_last_15_months, 13)
    @actions_created_avg_last12months_array = compute_running_avg_array(created_in_last_15_months, 13)

    # interpolate avg for current month.
    @interpolated_actions_created_this_month = interpolate_avg_for_current_month(@actions_created_last12months_array)
    @interpolated_actions_done_this_month = interpolate_avg_for_current_month(@actions_done_last12months_array)

    @created_count_array = Array.new(13, actions_last12months.created_after(@cut_off_year).count(:all)/12.0)
    @done_count_array    = Array.new(13, actions_last12months.completed_after(@cut_off_year).count(:all)/12.0)
    render :layout => false
  end

  def interpolate_avg_for_current_month(set)
    (set[0]*(1/percent_of_month) + set[1] + set[2]) / 3.0
  end

  def percent_of_month
    Time.zone.now.day / Time.zone.now.end_of_month.day.to_f
  end

  def actions_done_last_years
    @page_title = t('stats.index_title')
    @chart = Stats::Chart.new('actions_done_lastyears_data', :height => 400, :width => 900)
  end

  def actions_done_lastyears_data
    actions_last_months = current_user.todos.select("completed_at,created_at")

    month_count = difference_in_months(@today, actions_last_months.minimum(:created_at))
    # because this action is not scoped by date, the minimum created_at should always be
    # less than the minimum completed_at, so no reason to check minimum completed_at

    # convert to array and fill in non-existing months
    @actions_done_last_months_array = put_events_into_month_buckets(actions_last_months, month_count+1, :completed_at)
    @actions_created_last_months_array = put_events_into_month_buckets(actions_last_months, month_count+1, :created_at)

    # find max for graph in both hashes
    @max = (@actions_done_last_months_array + @actions_created_last_months_array).max

    # set running avg
    @actions_done_avg_last_months_array = compute_running_avg_array(@actions_done_last_months_array,month_count+1)
    @actions_created_avg_last_months_array = compute_running_avg_array(@actions_created_last_months_array,month_count+1)

    # interpolate avg for this month.
    @interpolated_actions_created_this_month = interpolate_avg_for_current_month(@actions_created_last_months_array)
    @interpolated_actions_done_this_month = interpolate_avg_for_current_month(@actions_done_last_months_array)

    @created_count_array = Array.new(month_count+1, actions_last_months.select { |x| x.created_at }.size/month_count)
    @done_count_array    = Array.new(month_count+1, actions_last_months.select { |x| x.completed_at }.size/month_count)

    render :layout => false
  end

  def actions_done_last30days_data
    # get actions created and completed in the past 30 days.
    @actions_done_last30days = current_user.todos.completed_after(@cut_off_30days).select("completed_at")
    @actions_created_last30days = current_user.todos.created_after(@cut_off_30days).select("created_at")

    # convert to array. 30+1 to have 30 complete days and one current day [0]
    @actions_done_last30days_array = convert_to_days_from_today_array(@actions_done_last30days, 31, :completed_at)
    @actions_created_last30days_array = convert_to_days_from_today_array(@actions_created_last30days, 31, :created_at)

    # find max for graph in both hashes
    @max = [@actions_done_last30days_array.max, @actions_created_last30days_array.max].max

    render :layout => false
  end

  def actions_completion_time_data
    @actions_completion_time = current_user.todos.completed.select("completed_at, created_at").reorder("completed_at DESC" )

    # convert to array and fill in non-existing weeks with 0
    @max_weeks = @actions_completion_time.last ? difference_in_weeks(@today, @actions_completion_time.last.completed_at) : 1
    @actions_completed_per_week_array = convert_to_weeks_running_array(@actions_completion_time, @max_weeks+1)

    # stop the chart after 10 weeks
    @count = [10, @max_weeks].min

    # convert to new array to hold max @cut_off elems + 1 for sum of actions after @cut_off
    @actions_completion_time_array = cut_off_array_with_sum(@actions_completed_per_week_array, @count)
    @max_actions = @actions_completion_time_array.max

    # get percentage done cumulative
    @cum_percent_done = convert_to_cumulative_array(@actions_completion_time_array, @actions_completion_time.count(:all))

    render :layout => false
  end

  def actions_running_time_data
    @actions_running_time = current_user.todos.not_completed.select("created_at").reorder("created_at DESC")

    # convert to array and fill in non-existing weeks with 0
    @max_weeks = difference_in_weeks(@today, @actions_running_time.last.created_at)
    @actions_running_per_week_array = convert_to_weeks_from_today_array(@actions_running_time, @max_weeks+1, :created_at)

    # cut off chart at 52 weeks = one year
    @count = [52, @max_weeks].min

    # convert to new array to hold max @cut_off elems + 1 for sum of actions after @cut_off
    @actions_running_time_array = cut_off_array_with_sum(@actions_running_per_week_array, @count)
    @max_actions = @actions_running_time_array.max

    # get percentage done cumulative
    @cum_percent_done = convert_to_cumulative_array(@actions_running_time_array, @actions_running_time.count )

    render :layout => false
  end

  def actions_visible_running_time_data
    # running means
    # - not completed (completed_at must be null)
    # visible means
    # - actions not part of a hidden project
    # - actions not part of a hidden context
    # - actions not deferred (show_from must be null)
    # - actions not pending/blocked

    @actions_running_time = current_user.todos.not_completed.not_hidden.not_deferred_or_blocked.
      select("todos.created_at").
      reorder("todos.created_at DESC")

    @max_weeks = difference_in_weeks(@today, @actions_running_time.last.created_at)
    @actions_running_per_week_array = convert_to_weeks_from_today_array(@actions_running_time, @max_weeks+1, :created_at)

    # cut off chart at 52 weeks = one year
    @count = [52, @max_weeks].min

    # convert to new array to hold max @cut_off elems + 1 for sum of actions after @cut_off
    @actions_running_time_array = cut_off_array_with_sum(@actions_running_per_week_array, @count)
    @max_actions = @actions_running_time_array.max

    # get percentage done cumulative
    @cum_percent_done = convert_to_cumulative_array(@actions_running_time_array, @actions_running_time.count )

    render :layout => false
  end

  def actions_open_per_week_data
    @actions_started = current_user.todos.created_after(@today-53.weeks).
      select("todos.created_at, todos.completed_at").
      reorder("todos.created_at DESC")

    @max_weeks = difference_in_weeks(@today, @actions_started.last.created_at)

    # cut off chart at 52 weeks = one year
    @count = [52, @max_weeks].min

    @actions_open_per_week_array = convert_to_weeks_running_from_today_array(@actions_started, @max_weeks+1)
    @actions_open_per_week_array = cut_off_array(@actions_open_per_week_array, @count)
    @max_actions = (@actions_open_per_week_array.max or 0)

    render :layout => false
  end

  def context_total_actions_data
    actions = Stats::TopContextsQuery.new(current_user).result

    @data = Stats::PieChartData.new(actions, t('stats.spread_of_actions_for_all_context'), 70)

    render :pie_chart_data, :layout => false
  end

  def context_running_actions_data
    actions = Stats::TopContextsQuery.new(current_user, :running => true).result
    @data = Stats::PieChartData.new(actions, t('stats.spread_of_running_actions_for_visible_contexts'), 60)

    render :pie_chart_data, :layout => false
  end

  def actions_day_of_week_all_data
    @actions_creation_day = current_user.todos.select("created_at")
    @actions_completion_day = current_user.todos.completed.select("completed_at")

    # convert to array and fill in non-existing days
    @actions_creation_day_array = Array.new(7) { |i| 0}
    @actions_creation_day.each { |t| @actions_creation_day_array[ t.created_at.wday ] += 1 }
    @max = @actions_creation_day_array.max

    # convert to array and fill in non-existing days
    @actions_completion_day_array = Array.new(7) { |i| 0}
    @actions_completion_day.each { |t| @actions_completion_day_array[ t.completed_at.wday ] += 1 }
    @max = @actions_completion_day_array.max

    render :layout => false
  end

  def actions_day_of_week_30days_data
    @actions_creation_day = current_user.todos.created_after(@cut_off_month).select("created_at")
    @actions_completion_day = current_user.todos.completed_after(@cut_off_month).select("completed_at")

Downloads/tracks-2.3.0/app/helpers/stats_helper.rb
module StatsHelper

  def font_size(cloud, tag)
    9 + 2 * cloud.relative_size(tag)
  end

  def month_and_year_label(i)
    t('date.month_names')[ (Time.now.mon - i -1 ) % 12 + 1 ]+ " " + (Time.now - i.months).year.to_s
  end

  def array_of_month_and_year_labels(count)
    Array.new(count) { |i| month_and_year_label(i) }
  end

  def month_label(i)
    t('date.month_names')[ (Time.now.mon - i -1 ) % 12 + 1 ]
  end

  def array_of_month_labels(count)
    Array.new(count) { |i| month_label(i) }
  end

end

Downloads/tracks-2.3.0/app/views/stats/_actions.html.erb
<%= render :partial => 'time_to_complete', :locals => {:ttc => actions.ttc} -%>

<p><%= t('stats.actions_actions_avg_created_30days', :count => (actions.created_last30days*10.0/30.0).round/10.0 )%>
<%= t('stats.actions_avg_completed_30days', :count => (actions.done_last30days*10.0/30.0).round/10.0 )%>
<%= t('stats.actions_avg_created', :count => (actions.created_last12months*10.0/12.0).round/10.0 )%>
<%= t('stats.actions_avg_completed', :count => (actions.done_last12months*10.0/12.0).round/10.0 )%></p>

<% actions.completion_charts.each do |chart| %><%=
    render :partial => 'chart', :locals => {:chart => chart}
-%><% end %>

<br style="clear:both">

<% actions.timing_charts.each do |chart| %><%=
    render :partial => 'chart', :locals => {:chart => chart}
-%><% end %>

Downloads/tracks-2.3.0/app/views/stats/_contexts.html.erb
<% contexts.charts.each do |chart| %><%=
    render :partial => 'chart', :locals => {:chart => chart}
-%><% end %>

<br style="clear:both">

<%= render :partial => 'contexts_list', :locals => {:contexts => contexts.actions, :key => 'contexts'} -%>

<%= render :partial => 'contexts_list', :locals => {:contexts => contexts.running_actions, :key => 'visible_contexts_with_incomplete_actions'} -%>

Downloads/tracks-2.3.0/app/views/stats/_tags.html.erb
<div class="stats_module">
<h3><%= t("stats.tag_cloud#{key}_title") %></h3>
<p><%= t("stats.tag_cloud#{key}_description") %></p>
<p>
<%
  if tag_cloud.empty?
    t('stats.no_tags_available')
  else
    tag_cloud.tags.each do |t|
%> <%=
      link_to t.name, tag_path(t.name), {
        :style => "font-size: " + "#{font_size(tag_cloud, t)}pt",
        :title => "#{t.count} #{t('common.actions_midsentence', :count => t.count)}"}
-%> <%
      end
    end
-%>
</p>
</div>

Downloads/tracks-2.3.0/app/views/stats/_time_to_complete.html.erb
<p><%= t('stats.actions_avg_completion_time', :count => ttc.avg) %>
<%= t('stats.actions_min_max_completion_days', :max => ttc.max, :min => ttc.min) %>
<%= t('stats.actions_min_completion_time', :time => ttc.min_sec) %></p>

Downloads/tracks-2.3.0/app/views/stats/_totals.html.erb
<p><%= t('stats.totals_project_count', :count => totals.projects) %>
  <%= t('stats.totals_active_project_count', :count => totals.active_projects) %>,
  <%= t('stats.totals_hidden_project_count', :count => totals.hidden_projects) %>
  <%= t('stats.totals_completed_project_count', :count => totals.completed_projects) %></p>

<p><%= t('stats.totals_context_count', :count => totals.contexts) %>
<%= t('stats.totals_visible_context_count', :count => totals.visible_contexts) %>
<%= t('stats.totals_hidden_context_count', :count => totals.hidden_contexts) %>

<% unless totals.empty? -%>
<p><%= t('stats.totals_first_action', :date => format_date(totals.first_action_at)) %>
<%= t('stats.totals_action_count', :count => totals.all_actions) %>,
<%= t('stats.totals_actions_completed', :count => totals.completed_actions) %>

<p><%= t('stats.totals_incomplete_actions', :count => totals.incomplete_actions) %>
<%= t('stats.totals_deferred_actions', :count => totals.deferred_actions) %>
<%= t('stats.totals_blocked_actions', :count => totals.blocked_actions) %>
</p>

<p><%= t('stats.totals_tag_count', :count => totals.tags) %>
  <%= t('stats.totals_unique_tags', :count => totals.unique_tags) %>
<% end -%>

Downloads/tracks-2.3.0/app/views/stats/actions_completion_time_data.html.erb
<%-
time_labels         = Array.new(@count){ |i| "#{i}-#{i+1}" }
time_labels[0]      = t('stats.within_one')
time_labels[@count] = "> #{@count}"
-%>
&title=<%= t('stats.action_completion_time_title') %>,{font-size:16},&
&y_legend=<%= t('stats.legend.actions') %>,10,0x8010A0&
&y2_legend=<%= t('stats.legend.percentage') %>,10,0xFF0000&
&x_legend=<%= t('stats.legend.running_time') %>,12,0x736AFF&
&y_ticks=5,10,5&
&filled_bar=50,0x9933CC,0x8010A0&
&values=<%= @actions_completion_time_array.join(",")%>&
&line_2=2,0xFF0000&
&values_2=<%= @cum_percent_done.join(",")%>&
&x_labels=<%= time_labels.join(",")%>&
&y_min=0&
<%
# add one to @max for people who have no actions completed yet.
# OpenFlashChart cannot handle y_max=0
-%>
&y_max=<%=1+@max_actions+@max_actions/10-%>&
&show_y2=true&
&y2_lines=2&
&y2_min=0&
&y2_max=100&
&x_label_style=9,,2,1&

Downloads/tracks-2.3.0/app/views/stats/actions_day_of_week_30days_data.html.erb
&title=<%= t('stats.actions_dow_30days_title') %>,{font-size:16},&
&y_legend=<%= t('stats.actions_dow_30days_legend.number_of_actions') %>,10,0x736AFF&
&x_legend=<%= t('stats.actions_dow_30days_legend.day_of_week') %>,10,0x736AFF&
&y_ticks=5,10,5&
&filled_bar=50,0x9933CC,0x8010A0,<%= t('stats.labels.created') %>,8&
&filled_bar_2=50,0x0066CC,0x0066CC,<%= t('stats.labels.completed') %>,8&
&values=<%=  @actions_creation_day_array.join(",") %>&
&values_2=<%= @actions_completion_day_array.join(",") %>&
&x_labels=<%= t('date.day_names').join(",") %>&
&y_min=0&
<%
  # add one to @max for people who have no actions completed yet.
  # OpenFlashChart cannot handle y_max=0
-%>
&y_max=<%=@max+1 -%>&
&x_label_style=9,,2,1&

Downloads/tracks-2.3.0/app/views/stats/done.html.erb
<div id="display_box">
  <div class="container">
    <div class=add_note_link><%= link_to t('common.show_all'), done_todos_path%></div>
    <h2>
      <%= t('common.last') %> <%= t('states.completed_plural' )%> <%= t('common.actions') %>
    </h2>
    <% if @done_recently.empty? -%>
      <div class="message"><p><%= t('todos.no_last_completed_actions') %></p></div>
    <% else -%>
      <%= render :partial => "todos/todo", :collection => @done_recently, :locals => { :parent_container_type => "completed", :suppress_context => false, :suppress_project => false } %>
    <% end -%>
  </div>

  <div class="container">
    <div class=add_note_link><%= link_to t('common.show_all'), done_projects_path%></div>
    <h2>
      <%= t('common.last') %> <%= t('states.completed_plural' )%> <%= t('common.projects') %>
    </h2>
    <% if @last_completed_projects.empty? -%>
      <div class="message"><p><%= t('projects.no_last_completed_projects') %></p></div>
    <% else -%>
      <div id="list-completed-projects" class="project-list">
      <%= render :partial => '/projects/project_listing',
      :collection => @last_completed_projects,
      :locals => {:suppress_drag_handle => true}
      %>
    </div>
    <% end -%>
  </div>

  <div class="container">
    <div class=add_note_link><%= link_to t('common.show_all'), done_recurring_todos_path%></div>
    <h2>
      <%= t('common.last') %> <%= t('states.completed_plural' )%> <%= t('common.recurring_todos') %>
    </h2>
    <% if @last_completed_recurring_todos.empty? -%>
      <div class="message"><p><%= t('projects.no_last_completed_recurring_todos') %></p></div>
    <% else -%>
      <%= render :partial => @last_completed_recurring_todos %>
    <% end -%>
  </div>

</div>

Downloads/tracks-2.3.0/app/views/stats/show_selection_from_chart.html.erb
<%= render :partial => 'chart', :locals => {:chart => @chart} -%>
<br/>
<p>
<%= t('stats.click_to_update_actions') %> <%= raw t('stats.click_to_return', :link => link_to(t('stats.click_to_return_link'), stats_path)) %>
<%
    unless @further
-%>
<%= raw t('stats.click_to_show_actions_from_week',
      :link => link_to("here", show_actions_from_chart_path(:id=>"#{params[:id]}_end", :index => params[:index])),
      :week => params[:index])
-%>
<%
    end
-%>
</p>
<br/>
<div class="container tickler" id="tickler_container">
  <h2><%= @page_title -%></h2>
  <div id="tickler" class="items toggle_target">
    <div id="tickler-empty-nd" style="display:<%= @selected_actions.empty? ? 'block' : 'none'%>;">
      <div class="message"><p><%= t('stats.no_actions_selected') %></p></div>
    </div>
        <%= render :partial => "todos/todo", :collection => @selected_actions, :locals => { :parent_container_type => 'stats' } %>
  </div>
</div>