Downloads/tracks-2.3.0/config/routes.rb
Rails.application.routes.draw do
  mount Tolk::Engine => '/tolk', :as => 'tolk' if Rails.env=='development'

  root :to => 'todos#index'

  post 'mailgun/mime' => 'mailgun#mailgun'

  post 'login' => 'login#login'
  get 'login' => 'login#login'
  get 'login/check_expiry' => 'login#check_expiry'
  get 'logout' => 'login#logout'

  get "tickler" => "todos#list_deferred"
  get 'review' => "projects#review"
  get 'calendar' => "calendar#show"
  get 'done' => "stats#done", :as => 'done_overview'

  get 'search' => 'search#index'
  post 'search/results' => 'search#results', :via => 'post'

  get 'data' => "data#index"
  get 'data/csv_notes' => 'data#csv_notes'
  get 'data/yaml_export' => 'data#yaml_export'
  get 'data/xml_export' => 'data#xml_export'
  get 'data/csv_actions' => 'data#csv_actions'

  get 'integrations' => "integrations#index"
  get 'integrations/rest_api' => "integrations#rest_api", :as => 'rest_api_docs'
  post 'integrations/cloudmailin' => 'integrations#cloudmailin'
  get 'integrations/search_plugin' => "integrations#search_plugin", :as => 'search_plugin'
  get 'integrations/google_gadget.xml' => 'integrations#google_gadget', :as => 'google_gadget'

  get 'preferences' => "preferences#index"
  get 'preferences/render_date_format' => "preferences#render_date_format"

  get 'feeds' => "feedlist#index", :as => 'feeds'
  get 'feedlist/get_feeds_for_context' => 'feedlist#get_feeds_for_context'
  get 'feedlist/get_feeds_for_project' => 'feedlist#get_feeds_for_project'

  get 'stats' => 'stats#index'
  get 'stats/actions_done_last12months_data' => 'stats#actions_done_last12months_data'
  get 'stats/actions_done_last_years' => 'stats#actions_done_last_years'
  get 'stats/actions_done_lastyears_data' => 'stats#actions_done_lastyears_data'
  get 'stats/actions_done_last30days_data' => 'stats#actions_done_last30days_data'
  get 'stats/actions_completion_time_data' => 'stats#actions_completion_time_data'
  get 'stats/actions_running_time_data' => 'stats#actions_running_time_data'
  get 'stats/actions_visible_running_time_data' => 'stats#actions_visible_running_time_data'
  get 'stats/actions_open_per_week_data' => 'stats#actions_open_per_week_data'
  get 'stats/context_total_actions_data' => 'stats#context_total_actions_data'
  get 'stats/context_running_actions_data' => 'stats#context_running_actions_data'
  get 'stats/actions_day_of_week_all_data' => 'stats#actions_day_of_week_all_data'
  get 'stats/actions_day_of_week_30days_data' => 'stats#actions_day_of_week_30days_data'
  get 'stats/actions_time_of_day_all_data' => 'stats#actions_time_of_day_all_data'
  get 'stats/actions_time_of_day_30days_data' => 'stats#actions_time_of_day_30days_data'
  get 'stats/show_selected_actions_from_chart/:id' => 'stats#show_selected_actions_from_chart', :as => 'show_actions_from_chart'

  resources :contexts do
    member do
      get 'done_todos'
      get 'all_done_todos'
    end
    collection do
      post 'order'
      get 'done'
    end
    resources :todos
  end

  resources :projects do
    member do
      get 'done_todos'
      get 'all_done_todos'
      get 'set_reviewed'  # TODO: convert to PUT/POST
    end
    collection do
      get 'done'
      post 'order'
      post 'alphabetize'
      post 'actionize'
    end
    resources :todos
  end

  resources :todos do
    member do
      put 'toggle_check'
      put 'toggle_star'
      put 'defer'
      get 'show_notes'
      get 'convert_to_project' # TODO: convert to PUT/POST
      delete 'remove_predecessor' # TODO: convert to PUT/POST
      post 'change_context'
    end
    collection do
      get 'done'
      get 'all_done'
      post 'check_deferred'
      post 'filter_to_context'
      post 'filter_to_project'
      post 'add_predecessor'
    end
  end

  # match /todos/tag and put everything in :name, including extensions like .m and .txt. 
  # This means the controller action needs to parse the extension and set format/content type
  # Needed for /todos/tag/first.last.m to work
  get 'todos/tag/:name' => 'todos#tag', :as => :tag, :format => false, :name => /.*/
  
  get 'tags.autocomplete' => "todos#tags", :format => 'autocomplete'
  get 'todos/done/tag/:name' => "todos#done_tag", :as => :done_tag
  get 'todos/all_done/tag/:name' => "todos#all_done_tag", :as => :all_done_tag
  get 'auto_complete_for_predecessor' => 'todos#auto_complete_for_predecessor'
  get 'mobile' => 'todos#index', :format => 'm'
  get 'm' => 'todos#index', :format => 'm'

  resources :recurring_todos do
    member do
      put 'toggle_check'
      put 'toggle_star'
    end
    collection do
      get 'done'
    end
  end

  resources :users do
    member do
      get 'change_password'
      get 'change_auth_type'
      get 'complete'
      post 'update_password'
      post 'update_auth_type'
      post 'refresh_token'
    end
  end
  get 'signup' => "users#new"

  resources :notes
  resources :preferences

  resources :data do
    collection do
      get :import
      post :csv_map
      post :csv_import
    end
  end

end

Downloads/tracks-2.3.0/app/controllers/integrations_controller.rb
class IntegrationsController < ApplicationController
  require 'mail'

  skip_before_filter :login_required, :only => [:cloudmailin, :search_plugin, :google_gadget]
  skip_before_filter :verify_authenticity_token, only: [:cloudmailin]

  def index
    @page_title = 'TRACKS::Integrations'
  end

  def rest_api
    @page_title = 'TRACKS::REST API Documentation'
  end

  def search_plugin
    @icon_data = [File.open(File.join(Rails.root, 'app', 'assets', 'images', 'done.png')).read].
      pack('m').gsub(/\n/, '')
  end

  def google_gadget
    render :layout => false, :content_type => Mime::XML
  end

  def cloudmailin
    if !verify_cloudmailin_signature
      render :text => "Message signature verification failed.", :status => 403
      return false
    end

    if process_message(params[:message])
      render :text => 'success', :status => 200
    else
      render :text => "No user found or other error", :status => 404
    end
  end

  private

  def process_message(message)
    MessageGateway::receive(Mail.new(message))
  end

  def verify_cloudmailin_signature
    provided = request.request_parameters.delete(:signature)
    signature = Digest::MD5.hexdigest(flatten_params(request.request_parameters).sort.map{|k,v| v}.join + SITE_CONFIG['cloudmailin'])
    return provided == signature
  end

  def flatten_params(params, title = nil, result = {})
    params.each do |key, value|
      if value.kind_of?(Hash)
        key_name = title ? "#{title}[#{key}]" : key
        flatten_params(value, key_name, result)
      else
        key_name = title ? "#{title}[#{key}]" : key
        result[key_name] = value
      end
    end

    return result
  end

end

Downloads/tracks-2.3.0/app/helpers/integrations_helper.rb
module IntegrationsHelper
end

Downloads/tracks-2.3.0/app/views/integrations/google_gadget.erb
<Module>
  <ModulePrefs title="Tracks" directory_title="Tracks" description="<%= t('integrations.gmail_description') %>" author="Tracks" author_email="butshesagirl@rousette.org.uk" author_affiliation="Tracks" author_location="UK" title_url="http://www.getontracks.org/" screenshot="http://www.getontracks.org/images/screens/tracks_home.png" thumbnail="http://www.getontracks.org/images/screens/tracks_home_thumb.png" category="communication" category2="tools" height="300">
  </ModulePrefs>
  <Content type="url" href="<%= root_url %>mobile"/>
</Module>

Downloads/tracks-2.3.0/app/views/integrations/index.de.html.erb
<% has_contexts = !current_user.contexts.empty? -%>
<h1>Integration</h1>
<p>Tracks kann mit verschiedenen Werkzeugen zusammenarbeiten...
  was immer Sie brauchen, um Ihre Aufgaben zu erledigen!
  Auf dieser Seite finden Sie Informationen, um einige dieser Werkzeuge einzurichten.
  Diese Beispiele sind nicht unbedingt auf Ihre Umgebung anwendbar oder bed&uuml;rfen mehr
  technisches Wissen als andere.
  Weitere Informationen finden Sie in der <%= link_to "Entwickler Documentation der Tracks' REST API", url_for(:action => 'rest_api') %> (englisch).</p>
<br/><p>Inhalt:</p>
<ul>
  <li><a href="#email-cron-section">Anstehende Aufgaben automatisch sich via E-Mail zusenden lassen</a></li>
  <li><a href="#message_gateway">Tracks mit einem Mail-Server integrieren, um Aufgaben via E-Mail zu erstellen</a></li>
  <li><a href="#google_gadget">Tracks zu Ihrer Google Gmail Seite hinzuf&uuml;gen</a></li>
</ul><br/>
<p>Sie haben weitere Beispiele?
  <a href="http://www.getontracks.org/forums/viewforum/10/" title="Tracks | Tips and Tricks">Berichten Sie uns
    in unserem Tipps&amp;Tricks Forum</a>, damit wir es f&uuml;r die n&auml;chsten Versionen ber&uuml;cksichtigen k&ouml;nnen.
</p>

<a name="email-cron-section"> </a>
<h2>Automatically Email Yourself Upcoming Actions</h2>

<p>If you enter the following entry to your crontab, you will receive email every day around 5 AM with a list of the upcoming actions which are due within the next 7 days.</p>

<textarea id="cron" name="cron">0 5 * * * /usr/bin/curl -0 "<%= root_url %>todos.txt?due=6&token=<%= current_user.token %>" | /usr/bin/mail -e -s 'Tracks actions due in the next 7 days' youremail@yourdomain.com</textarea>

<p>You can of course use other text <%= link_to 'feeds provided by Tracks', feeds_path %> -- why not email a list of next actions in a particular project to a group of colleagues who are working on the project?</p>

<a name="message_gateway"> </a>
<h2>Integrated email/SMS receiver</h2>
<p>
  If Tracks is running on the same server as your mail server, you can use the integrated mail handler built into tracks. Steps to set it up:
</p>
<ul>
  <li>Go to <%= link_to t('layouts.navigation.preferences'), preferences_url %> and
    set your "<%= Preference.human_attribute_name('sms_email') %>" and
    "<%= Preference.human_attribute_name('sms_context') %>" for todos sent in
    via email (which could come from an SMS message)</li>
  <li>In sendmail/qmail/postfix/whatever, set up an email address
    alias to pipe messages to <pre>/PATH/TO/TRACKS/bin/rails r -e production 'MessageGateway.receive(STDIN.read)'</pre></li>
  <li>Send an email to your newly configured address!</li>
</ul>
<p>You can also use the Rich Todo API to send in tasks like "do laundry @ Home"
  or "Call Bill > project X". The subject of the message will fill description,
  context, and project, while the body will populate the tasks's note.
</p>
<p>
  You may need to configure your <tt>site.yml</tt> to tell the message gateway to look at the <tt>to:</tt> field or <tt>from:</tt> field to
  lookup Tracks' user from the email address in that field. </p>
  <p>You can also send all email to a specific Tracks user. Configure mail_dispatch in site.yml to <tt>single_user</tt> and pass the login of the user:
    <pre>TRACKS_MAIL_RECEIVER=<%=current_user.login%> /PATH/TO/TRACKS/bin/rails r -e production 'MessageGateway.receive(STDIN.read)'</pre>
</p>

<a name="google_gadget"> </a>
<h2>Add Tracks as a Google Gmail gadget</h2>
<p>
  You can now manage your projects/actions inside Gmail using Tracks Gmail Gadget.
  Add Tracks Gmail gadget to the sidebar of Gmail and track your next actions
  or add new action without explicitly open new browser tab for Tracks. Steps to set it up:
</p>
<ul>
  <li>Sign in to Gmail and click Settings in the top right of your Gmail page. In Gmail setting page, click Labs tab</li>
  <li>Enable the "Add any gadget by URL" feature. You will find it at bottom of the list. Select Enable radio button and click Save Changes button.</li>
  <li>Now you can see Gadgets tab added to Gmail Settings. Go to the Gadgets tab</li>
  <li>Paste following link to the Add a gadget by its URL: and then click Add button:<br/>
    <pre><%= integrations_url + "/google_gadget.xml" %></pre></li>
</ul>

Downloads/tracks-2.3.0/app/views/integrations/index.en.html.erb
<% has_contexts = !current_user.contexts.empty? -%>
<h1>Integrations</h1>
<p>Tracks can be integrated with a number of other tools...
  whatever it takes to help you get things done!
  This page has information on setting up some of these.
  Not all of these are applicable to all platforms, and some require more
  technical knowledge than others.
  See also <%= link_to "developer documentation for Tracks' REST API", url_for(:action => 'rest_api') %>.</p>
<br/><p>Contents:</p>
<ul>
  <li><a href="#email-cron-section">Automatically Email Yourself Upcoming Actions</a></li>
  <li><a href="#message_gateway">Integrate Tracks with an email server to be able to send an action through email to Tracks</a></li>
  <li><a href="#mailgun">Send emails to Tracks with Mailgun</a>
  <li><a href="#todo_rich_message_format">Rich Todo Message email format</a>
  <li><a href="#google_gadget">Add Tracks as a Google Gmail gadget</a></li>
</ul><br/>
<p>Do you have one of your own to add?
  <a href="http://www.getontracks.org/forums/viewforum/10/" title="Tracks | Tips and Tricks">Tell us about
    it in our Tips and Tricks forum</a> and we may include it on this page in a future versions of Tracks.
</p>

<a name="email-cron-section"> </a>
<h2>Automatically Email Yourself Upcoming Actions</h2>

<p>If you enter the following entry to your crontab, you will receive email every day around 5 AM with a list of the upcoming actions which are due within the next 7 days.</p>

<textarea id="cron" name="cron">0 5 * * * /usr/bin/curl -0 "<%= root_url %>todos.txt?due=6&token=<%= current_user.token %>" | /usr/bin/mail -e -s 'Tracks actions due in the next 7 days' youremail@yourdomain.com</textarea>

<p>You can of course use other text <%= link_to 'feeds provided by Tracks', feeds_path %> -- why not email a list of next actions in a particular project to a group of colleagues who are working on the project?</p>

<a name="message_gateway"> </a>
<h2>Integrated email/SMS receiver</h2>
<p>
  If Tracks is running on the same server as your mail server, you can use the integrated mail handler built into tracks. Steps to set it up:
</p>
<ul>
  <li>Go to <%= link_to t('layouts.navigation.preferences'), preferences_url %> and
    set your "<%= Preference.human_attribute_name('sms_email') %>" and
    "<%= Preference.human_attribute_name('sms_context') %>" for todos sent in
    via email (which could come from an SMS message)</li>
  <li>In sendmail/qmail/postfix/whatever, set up an email address
    alias to pipe messages to <pre>/PATH/TO/TRACKS/bin/rails r -e production 'MessageGateway.receive(STDIN.read)'</pre></li>
  <li>Send an email to your newly configured address!</li>
</ul>
<p>You can also use the Rich Todo API to send in tasks like "do laundry @ Home"
  or "Call Bill > project X". The subject of the message will fill description,
  context, and project, while the body will populate the tasks's note.
</p>
<p>
  You may need to configure your <tt>site.yml</tt> to tell the message gateway to look at the <tt>to:</tt> field or <tt>from:</tt> field to
  lookup Tracks' user from the email address in that field. </p>
  <p>You can also send all email to a specific Tracks user. Configure mail_dispatch in site.yml to <tt>single_user</tt> and pass the login of the user:
    <pre>TRACKS_MAIL_RECEIVER=<%=current_user.login%> /PATH/TO/TRACKS/bin/rails r -e production 'MessageGateway.receive(STDIN.read)'</pre>
</p>

<a name="mailgun"> </a>
<h2>Send emails to Tracks with Mailgun</h2>
<p>
If you want to email tasks to Tracks, but cannot run a mailserver on the same host,
you could use the <a href='www.mailgun.com'>Mailgun</a> support built in to Tracks.
</p>
<p>
For this to work your Tracks server will need to be reachable from the internet, so
that Mailgun can POST data to it.
<p>
<ul>
  <li>Go to <%= link_to 'http://mailgun.com' %> and register for a free account.</li>
  <li>Go to 'Routes' in the Mailgun control panel, and add a new route:</li>
  <ul>
    <li>'Filter expression' should be set to 'catch_all()'</li>
    <li>'Action' should be 'forward("http://mytracksserver.domain.com/mailgun/mime")'
  </ul>
  <li>Go to <%= link_to t('layouts.navigation.preferences'), preferences_url %> and
    enter your incoming Mailgun email address (e.g. tracks@user.mailgun.com) in the
    "<%= Preference.human_attribute_name('sms_email') %>" box.</li>
  <li>Select a default context for emails to be put in with
    "<%= Preference.human_attribute_name('sms_context') %>"</li>
  <li>Add your Mailgun API key (not the Public API key) to the Tracks 'site.yml'
  <li>Update the mailmap in 'site.yml' to define which senders can send emails to
    which incoming addresses. For example, to send emails from your work and home
    email accounts to your tracks Mailgun route, set it up like this:
    <pre class=code>
mailmap:
  tracks@user.mailgun.org:
  - me@myhome.domain.net
  - mr.user@work.company.com
</pre>
</ul>
<p>All the comments about the email format from the section above apply to the
Mailgun handling, as the data is processed the same way</p>

<a name="todo_rich_message_format"> </a>
<h2>Rich Todo Message Format</h2>
<p> For both of the above methods, the follow format can be used:</p>
<pre>my awesome todo @context ~project &lt;131012 &gt;131009 #tag1 #tag2 *</pre>
<p>The fields are:</p>
<table>
  <tr>
    <th>Symbol</th><th>Meaning</th>
  </tr>
  <tr>
    <td>@</td><td>The context to place the Todo in</td>
  </tr>
  <tr>
    <td>~</td><td>The project to place the Todo in</td>
  </tr>
  <tr>
    <td>&lt;</td><td>The due date for the Todo (may be 2 digits for day, 4 digits for month-day, or 6 digits for yeah-month-day)</td>
  </tr>
  <tr>
    <td>&gt;</td><td>The due date for the Todo (may be 2 digits for day, 4 digits for month-day, or 6 digits for yeah-month-day)</td>
  </tr>
  <tr>
    <td>#</td><td>A tag to apply to the Todo - may be used multiple times</td>
  </tr>
  <tr>
    <td>*</td><td>Flag to star the Todo</td>
  </tr>
</table>
<p>All symbols are optional, and text up to the first symbol (or end of string) is used as the description of the todo</p>

<a name="google_gadget"> </a>
<h2>Add Tracks as a Google Gmail gadget</h2>
<p>
  You can now manage your projects/actions inside Gmail using Tracks Gmail Gadget.
  Add Tracks Gmail gadget to the sidebar of Gmail and track your next actions
  or add new action without explicitly open new browser tab for Tracks. Steps to set it up:
</p>
<ul>
  <li>Sign in to Gmail and click Settings in the top right of your Gmail page. In Gmail setting page, click Labs tab</li>
  <li>Enable the "Add any gadget by URL" feature. You will find it at bottom of the list. Select Enable radio button and click Save Changes button.</li>
  <li>Now you can see Gadgets tab added to Gmail Settings. Go to the Gadgets tab</li>
  <li>Paste following link to the Add a gadget by its URL: and then click Add button:<br/>
    <pre><%= integrations_url + "/google_gadget" %></pre></li>
</ul>

Downloads/tracks-2.3.0/app/views/integrations/index.nl.html.erb
<% has_contexts = !current_user.contexts.empty? -%>
<h1>Integratie</h1>
<p>Tracks kan met een aantal tools worden geïntegreerd...
  Alles om je te helpen om dingen gedaan te krijgen!
  Deze pagina heeft informatie over het tot stand brengen van sommige integratievormen.
  Deze voorbeelden zijn niet altijd voor alle platformen van toepassing en
  sommige voorbeelden vragen meer technische kennis dan anderen
  Zie ook <%= link_to "de documentatie voor ontwikkelaars met Tracks' REST API", url_for(:action => 'rest_api') %>.</p>
<br/><p>Inhoud:</p>
<ul>
  <li><a href="#email-cron-section">Email jezelf automatisch de acties met een aflopende deadline</a></li>
  <li><a href="#message_gateway">Integreer Tracks met een email server om een actie via email naar Tracks te sturen</a></li>
  <li><a href="#google_gadget">Voeg tracks toe als een Google Gmail gadget</a></li>
</ul><br/>
<p>Heb je een tip om hier toe te voegen?
  <a href="http://www.getontracks.org/forums/viewforum/10/" title="Tracks | Tips and Tricks">Vertel ons er over in onze
    Tips and Tricks forum</a> en misschien voegen we jouw tip toe op deze pagina in een toekomstige versie van Tracks.
</p>

<a name="email-cron-section"> </a>
<h2>Email jezelf automatisch de acties met een aflopende deadline</h2>

<p>Als je de volgende regel toevoegd aan jouw crontab, dat ontvang je een e-mail op elke dag rond 05:00 met een lijst met acties waarvan de deadline afloopt binnen de komende 7 dagen.</p>

<textarea id="cron" name="cron">0 5 * * * /usr/bin/curl -0 "<%= root_url %>todos.txt?due=6&token=<%= current_user.token %>" | /usr/bin/mail -e -s 'Tracks actions due in the next 7 days' youremail@yourdomain.com</textarea>

<p>Uiteraard kan je ook een andere <%= link_to 'text feed gebruiken die Tracks biedt', feeds_path %> -- bijvoorbeeld een email met een lijst van acties voor een specifiek project naar een groep collega's die werken aan dat project?</p>

<a name="message_gateway"> </a>
<h2>Integreer Tracks met een email server om een actie via email naar Tracks te sturen</h2>
<p>
  Als Tracks draait op dezelfde server als jouw mailserver, dan kan je de geïntegreerde mail handler gebruiken van Tracks. Om dit in te stellen:
</p>
<ul>
  <li>Ga naar <%= link_to t('layouts.navigation.preferences'), preferences_url %>
    en stel in "<%= Preference.human_attribute_name('sms_email') %>" en
    "<%= Preference.human_attribute_name('sms_context') %>" voor acties die
    verzonden zijn via email (die bijv. komen via een SMS message)</li>
  <li>In sendmail/qmail/postfix/whatever, stel een email address
    alias in om berichten door te sturen naar
    <pre>/PATH/TO/TRACKS/bin/rails r -e production 'MessageGateway.receive(STDIN.read)'</pre></li>
  <li>Verstuur een email naar het net geconfigureerde e-mail adres!</li>
</ul>
<p>Je kan ook de Rich Todo API gebruiken om acties te maken zoals "do laundry @ Home"
  of "Call Bill > project X". Het onderwerp van het bericht zal de bijschrijving van de actie vullen,
  de context, en het project, terwijl de body van het bericht de notities van de actie zal vullen.
</p>
<p>
  Het kan nodig zijn om jouw <tt>site.yml</tt> te configureren om de message gateway te laten kijken naar het <tt>to:</tt> veld of het <tt>from:</tt> veld om
  de Tracks-gebruiker op te zoeken met het emailadres uit dat veld. </p>
  <p>Je kan ook alle email naar een specifieke Tracks gebruiker sturen. Stel mail_dispatch in site.yml in op <tt>single_user</tt> en geeft de login van de gebruiker door:
    <pre>TRACKS_MAIL_RECEIVER=<%=current_user.login%> /PATH/TO/TRACKS/bin/rails r -e production 'MessageGateway.receive(STDIN.read)'</pre>
</p>

<a name="google_gadget"> </a>
<h2>Voeg tracks toe als een Google Gmail gadget</h2>
<p>
  Je kan nu ook jouw projects/actions beheren in Gmail met de Tracks Gmail Gadget.
  Voeg Tracks Gmail gadget toe aan de sidebar van Gmail en volg jouw acties
  of voeg een nieuwe actie toe zonder apart een nieuw browser tab/scherm te openen
  voor Tracks. Om dit in te stellen:
</p>
<ul>
  <li>Log bij Gmail in en kies Settings in de rechter-bovenkant van jouw Gmail pagina. In de Gmail setting pagina, kies de Labs tab</li>
  <li>Zet de "Add any gadget by URL" feature aan. Deze kan je onderop de lijst vinden. Kies voor Enable and kies Save Changes.</li>
  <li>Nu zie je dat de Gadgets tab is toegevoegd aan de Gmail Settings. Ga nu naar de Gadgets tab</li>
  <li>Knip en plak de volgende link in de Add a gadget by its URL: en klik dan op de Add button:<br/>
    <pre><%= integrations_url + "/google_gadget" %></pre></li>
</ul>