Downloads/tracks-2.3.0/config/routes.rb
Rails.application.routes.draw do
  mount Tolk::Engine => '/tolk', :as => 'tolk' if Rails.env=='development'

  root :to => 'todos#index'

  post 'mailgun/mime' => 'mailgun#mailgun'

  post 'login' => 'login#login'
  get 'login' => 'login#login'
  get 'login/check_expiry' => 'login#check_expiry'
  get 'logout' => 'login#logout'

  get "tickler" => "todos#list_deferred"
  get 'review' => "projects#review"
  get 'calendar' => "calendar#show"
  get 'done' => "stats#done", :as => 'done_overview'

  get 'search' => 'search#index'
  post 'search/results' => 'search#results', :via => 'post'

  get 'data' => "data#index"
  get 'data/csv_notes' => 'data#csv_notes'
  get 'data/yaml_export' => 'data#yaml_export'
  get 'data/xml_export' => 'data#xml_export'
  get 'data/csv_actions' => 'data#csv_actions'

  get 'integrations' => "integrations#index"
  get 'integrations/rest_api' => "integrations#rest_api", :as => 'rest_api_docs'
  post 'integrations/cloudmailin' => 'integrations#cloudmailin'
  get 'integrations/search_plugin' => "integrations#search_plugin", :as => 'search_plugin'
  get 'integrations/google_gadget.xml' => 'integrations#google_gadget', :as => 'google_gadget'

  get 'preferences' => "preferences#index"
  get 'preferences/render_date_format' => "preferences#render_date_format"

  get 'feeds' => "feedlist#index", :as => 'feeds'
  get 'feedlist/get_feeds_for_context' => 'feedlist#get_feeds_for_context'
  get 'feedlist/get_feeds_for_project' => 'feedlist#get_feeds_for_project'

  get 'stats' => 'stats#index'
  get 'stats/actions_done_last12months_data' => 'stats#actions_done_last12months_data'
  get 'stats/actions_done_last_years' => 'stats#actions_done_last_years'
  get 'stats/actions_done_lastyears_data' => 'stats#actions_done_lastyears_data'
  get 'stats/actions_done_last30days_data' => 'stats#actions_done_last30days_data'
  get 'stats/actions_completion_time_data' => 'stats#actions_completion_time_data'
  get 'stats/actions_running_time_data' => 'stats#actions_running_time_data'
  get 'stats/actions_visible_running_time_data' => 'stats#actions_visible_running_time_data'
  get 'stats/actions_open_per_week_data' => 'stats#actions_open_per_week_data'
  get 'stats/context_total_actions_data' => 'stats#context_total_actions_data'
  get 'stats/context_running_actions_data' => 'stats#context_running_actions_data'
  get 'stats/actions_day_of_week_all_data' => 'stats#actions_day_of_week_all_data'
  get 'stats/actions_day_of_week_30days_data' => 'stats#actions_day_of_week_30days_data'
  get 'stats/actions_time_of_day_all_data' => 'stats#actions_time_of_day_all_data'
  get 'stats/actions_time_of_day_30days_data' => 'stats#actions_time_of_day_30days_data'
  get 'stats/show_selected_actions_from_chart/:id' => 'stats#show_selected_actions_from_chart', :as => 'show_actions_from_chart'

  resources :contexts do
    member do
      get 'done_todos'
      get 'all_done_todos'
    end
    collection do
      post 'order'
      get 'done'
    end
    resources :todos
  end

  resources :projects do
    member do
      get 'done_todos'
      get 'all_done_todos'
      get 'set_reviewed'  # TODO: convert to PUT/POST
    end
    collection do
      get 'done'
      post 'order'
      post 'alphabetize'
      post 'actionize'
    end
    resources :todos
  end

  resources :todos do
    member do
      put 'toggle_check'
      put 'toggle_star'
      put 'defer'
      get 'show_notes'
      get 'convert_to_project' # TODO: convert to PUT/POST
      delete 'remove_predecessor' # TODO: convert to PUT/POST
      post 'change_context'
    end
    collection do
      get 'done'
      get 'all_done'
      post 'check_deferred'
      post 'filter_to_context'
      post 'filter_to_project'
      post 'add_predecessor'
    end
  end

  # match /todos/tag and put everything in :name, including extensions like .m and .txt. 
  # This means the controller action needs to parse the extension and set format/content type
  # Needed for /todos/tag/first.last.m to work
  get 'todos/tag/:name' => 'todos#tag', :as => :tag, :format => false, :name => /.*/
  
  get 'tags.autocomplete' => "todos#tags", :format => 'autocomplete'
  get 'todos/done/tag/:name' => "todos#done_tag", :as => :done_tag
  get 'todos/all_done/tag/:name' => "todos#all_done_tag", :as => :all_done_tag
  get 'auto_complete_for_predecessor' => 'todos#auto_complete_for_predecessor'
  get 'mobile' => 'todos#index', :format => 'm'
  get 'm' => 'todos#index', :format => 'm'

  resources :recurring_todos do
    member do
      put 'toggle_check'
      put 'toggle_star'
    end
    collection do
      get 'done'
    end
  end

  resources :users do
    member do
      get 'change_password'
      get 'change_auth_type'
      get 'complete'
      post 'update_password'
      post 'update_auth_type'
      post 'refresh_token'
    end
  end
  get 'signup' => "users#new"

  resources :notes
  resources :preferences

  resources :data do
    collection do
      get :import
      post :csv_map
      post :csv_import
    end
  end

end

Downloads/tracks-2.3.0/app/models/context.rb
class Context < ActiveRecord::Base

  has_many :todos, -> { order("todos.due IS NULL, todos.due ASC, todos.created_at ASC").includes(:project) }, :dependent => :delete_all
  has_many :recurring_todos, :dependent => :delete_all
  belongs_to :user

  scope :active,    -> { where state: :active }
  scope :hidden,    -> { where state: :hidden }
  scope :closed,    -> { where state: :closed }
  scope :with_name, lambda { |name| where("name LIKE ?", name) }

  acts_as_list :scope => :user, :top_of_list => 0

  # state machine
  include AASM

  aasm :column => :state do

    state :active, :initial => true
    state :closed
    state :hidden

    event :close do
      transitions :to => :closed, :from => [:active, :hidden], :guard => :no_active_todos?
    end

    event :hide do
      transitions :to => :hidden, :from => [:active, :closed]
    end

    event :activate do
      transitions :to => :active, :from => [:closed, :hidden]
    end
  end

  validates_presence_of :name, :message => "context must have a name"
  validates_length_of :name, :maximum => 255, :message => "context name must be less than 256 characters"
  validates_uniqueness_of :name, :message => "already exists", :scope => "user_id"

  def self.null_object
    NullContext.new
  end

  def title
    name
  end

  def new_record_before_save?
    @new_record_before_save
  end

  def no_active_todos?
    return todos.active.count == 0
  end

end

class NullContext

  def nil?
    true
  end

  def id
    nil
  end

  def name
    ''
  end

end

Downloads/tracks-2.3.0/app/models/stats/contexts.rb
module Stats
  class Contexts

    attr_reader :user
    def initialize(user)
      @user = user
    end

    def actions
      @actions ||= Stats::TopContextsQuery.new(user, :limit => 5).result
    end

    def running_actions
      @running_actions ||= Stats::TopContextsQuery.new(user, :limit => 5, :running => true).result
    end

    def charts
      @charts = %w{
        context_total_actions_data
        context_running_actions_data
      }.map do |action|
        Stats::Chart.new(action, :height => 325)
      end
    end

  end
end

Downloads/tracks-2.3.0/app/controllers/contexts_controller.rb
class ContextsController < ApplicationController

  helper :todos

  before_filter :init, :except => [:index, :create, :destroy, :order]
  before_filter :set_context_from_params, :only => [:update, :destroy]
  skip_before_filter :login_required, :only => [:index]
  prepend_before_filter :login_or_feed_token_required, :only => [:index]

  def index
    @all_contexts    = current_user.contexts
    @active_contexts = current_user.contexts.active
    @hidden_contexts = current_user.contexts.hidden
    @closed_contexts = current_user.contexts.closed
    init_not_done_counts(['context']) unless request.format == :autocomplete

    respond_to do |format|
      format.html &render_contexts_html
      format.m    &render_contexts_mobile
      format.xml  { render :xml => @all_contexts.to_xml( :except => :user_id ) }
      format.any(:rss, :atom) do
        @feed_title = 'Tracks Contexts'
        @feed_description = "Lists all the contexts for #{current_user.display_name}"
      end
      format.text do
        # somehow passing Mime::TEXT using content_type to render does not work
        headers['Content-Type']=Mime::TEXT.to_s
        render :action => 'index', :layout => false, :content_type => Mime::TEXT
      end
      format.autocomplete &render_autocomplete
    end
  end

  def show
    set_context_from_params

    unless @context.nil?
      @max_completed = current_user.prefs.show_number_completed
      @done = @context.todos.completed.limit(@max_completed).reorder("todos.completed_at DESC, todos.created_at DESC").includes(Todo::DEFAULT_INCLUDES)
      @not_done_todos = @context.todos.active.reorder("todos.due IS NULL, todos.due ASC, todos.created_at ASC").includes(Todo::DEFAULT_INCLUDES)
      @todos_without_project = @not_done_todos.select{|t| t.project.nil?}

      @deferred_todos = @context.todos.deferred.includes(Todo::DEFAULT_INCLUDES)
      @pending_todos = @context.todos.pending.includes(Todo::DEFAULT_INCLUDES)

      @projects = current_user.projects
      @contexts = current_user.contexts

      @projects_to_show = @projects.active
      @contexts_to_show = [@context]

      @count = @not_done_todos.count + @deferred_todos.count + @pending_todos.count
      @page_title = "TRACKS::Context: #{@context.name}"
      respond_to do |format|
        format.html
        format.m    &render_context_mobile
        format.xml  { render :xml => @context.to_xml( :except => :user_id ) }
      end
    else
      respond_to do |format|
        format.html { render :text => 'Context not found', :status => 404 }
        format.xml  { render :xml => '<error>Context not found</error>', :status => 404 }
      end
    end
  end

  def create
    if params[:format] == 'application/xml' && params['exception']
      render_failure "Expected post format is valid xml like so: <context><name>context name</name></context>.", 400
      return
    end
    @context = current_user.contexts.build(context_params)
    @context.hide! if params['context_state'] && params['context_state']['hide'] == '1'
    @saved = @context.save
    @context_not_done_counts = { @context.id => 0 }
    respond_to do |format|
      format.js do
        @down_count = current_user.contexts.size
        init_not_done_counts
      end
      format.xml do
        if @context.new_record?
          render_failure @context.errors.to_xml.html_safe, 409
        else
          head :created, :location => context_url(@context)
        end
      end
    end
  end

  # Edit the details of the context
  #
  def update
    process_params_for_update

    @context.attributes = context_params
    @saved = @context.save
    @state_saved = set_state_for_update(@new_state)
    @saved = @saved && @state_saved

    if @saved
      @state_changed = (@original_context_state != @context.state)
      @new_state = @context.state if @state_changed
      @active_contexts = current_user.contexts.active
      @hidden_contexts = current_user.contexts.hidden
      @closed_contexts = current_user.contexts.closed
    end

    respond_to do |format|
      format.js
      format.xml {
          if @saved
            render :xml => @context.to_xml( :except => :user_id )
          else
            render :text => "Error on update: #{@context.errors.full_messages.inject("") {|v, e| v + e + " " }}", :status => 409
          end
        }
    end
  end

  def edit
    @context = Context.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  # Fairly self-explanatory; deletes the context If the context contains
  # actions, you'll get a warning dialogue. If you choose to go ahead, any
  # actions in the context will also be deleted.
  def destroy
    # make sure the deleted recurring patterns are removed from associated todos
    @context.recurring_todos.each { |rt| rt.clear_todos_association } unless @context.recurring_todos.nil?

    @context.destroy
    respond_to do |format|
      format.js do
        @down_count = current_user.contexts.size
        update_state_counts
      end
      format.xml { render :text => "Deleted context #{@context.name}" }
    end
  end

  # Methods for changing the sort order of the contexts in the list
  #
  def order
    context_ids = params["container_context"]
    @projects = current_user.contexts.update_positions( context_ids )
    render :nothing => true
  rescue
    notify :error, $!
    redirect_to :action => 'index'
  end

  def done_todos
    done_todos_for current_user.contexts.find(params[:id])
  end

  def all_done_todos
    all_done_todos_for current_user.contexts.find(params[:id])
  end

  private

  def context_params
    params.require(:context).permit(:name, :position, :state)
  end

  protected

  def update_state_counts
    @active_contexts_count = current_user.contexts.active.count
    @hidden_contexts_count = current_user.contexts.hidden.count
    @closed_contexts_count = current_user.contexts.closed.count
    @show_active_contexts = @active_contexts_count > 0
    @show_hidden_contexts = @hidden_contexts_count > 0
    @show_closed_contexts = @closed_contexts_count > 0
  end

  def render_contexts_html
    lambda do
      @page_title = "TRACKS::List Contexts"
      @no_active_contexts = @active_contexts.empty?
      @no_hidden_contexts = @hidden_contexts.empty?
      @no_closed_contexts = @closed_contexts.empty?
      @active_count = @active_contexts.size
      @hidden_count = @hidden_contexts.size
      @closed_count = @closed_contexts.size
      @count = @active_count + @hidden_count + @closed_count
      @new_context = current_user.contexts.build

      render
    end
  end

  def render_contexts_mobile
    lambda do
      @page_title = "TRACKS::List Contexts"
      @active_contexts = current_user.contexts.active
      @hidden_contexts = current_user.contexts.hidden
      @down_count = @active_contexts.size + @hidden_contexts.size
      cookies[:mobile_url]= {:value => request.fullpath, :secure => SITE_CONFIG['secure_cookies']}
      render
    end
  end

  def render_context_mobile
    lambda do
      @page_title = "TRACKS::List actions in "+@context.name
      @not_done = @not_done_todos.select {|t| t.context_id == @context.id }
      @down_count = @not_done.size
      cookies[:mobile_url]= {:value => request.fullpath, :secure => SITE_CONFIG['secure_cookies']}
      @mobile_from_context = @context.id
      render
    end
  end

  def render_autocomplete
    lambda do
      render :text => for_autocomplete(current_user.contexts, params[:term])
    end
  end

  def feed_options
    Context.feed_options(current_user)
  end

  def set_context_from_params
    @context = current_user.contexts.find(params[:id])
  rescue
    @context = nil
  end

  def init
    @source_view = params['_source_view'] || 'context'
    init_data_for_sidebar
  end

  def process_params_for_update
    params['context'] ||= {}
    @success_text = if params['field'] == 'name' && params['value']
      params['context']['id'] = params['id']
      params['context']['name'] = params['value']
    end

    @original_context_state = @context.state
    @new_state = params['context']['state']
    params['context'].delete('state')
  end

  def set_state_for_update(new_state)
    begin
      unless @original_context_state == new_state
        if new_state == 'active'
          @context.activate!
        elsif new_state == 'hidden'
          @context.hide!
        elsif new_state == 'closed'
          @context.close!
        end
      end
      return true
    rescue AASM::InvalidTransition
      @context.errors.add(:state, "cannot be changed. The context cannot be closed if you have uncompleted actions in this context")
      return false
    end
  end

end

Downloads/tracks-2.3.0/app/helpers/contexts_helper.rb
module ContextsHelper

  def show_context_name(context)
    if source_view_is :context
      content_tag(:span, :id => "context_name"){context.name}
    else
      link_to_context( context )
    end
  end

  def link_to_delete_context(context, descriptor = sanitize(context.name))
    link_to_delete(:context, context, descriptor)
  end

  def link_to_edit_context (context, descriptor = sanitize(context.name))
    link_to_edit(:context, context, descriptor)
  end

  def context_summary(context, undone_todo_count)
    content_tag(:p, "#{undone_todo_count}. Context is #{context.hidden? ? 'Hidden' : 'Active'}.".html_safe)
  end

end

Downloads/tracks-2.3.0/app/views/contexts/_context.html.erb
<%
@not_done = @not_done_todos.select {|t| t.context_id == context.id }
# invalidate the cache every day because of staleness or
# rendering of "due in x days" that change without touching updated at of the todo
cache [context, source_view_key, current_user.date.strftime("%Y%m%d"), @tag_name] do
-%>
  <%=
    render :partial => 'todos/collection',
      :object => @not_done,
      :locals => { :settings => {
        :id => "c#{context.id}",
        :collapsible => settings[:collapsible],
        :container_name => 'context',
        :title => show_context_name(context),
        :show_empty_containers => settings[:show_empty_containers],
        :parent_container_type => settings[:parent_container_type]
      }}
  %>
<% end %>

Downloads/tracks-2.3.0/app/views/contexts/_context.m.erb
<%
new_context_todo_params = {:format => :m}
new_context_todo_params[:from_context] = context.id

# select actions from this context
@not_done = @not_done_todos.select {|t| t.context_id == context.id }

if not @not_done.empty?
  # only show a context when there are actions in it
  -%>
<h2><%= link_to context.name, context_path(context, :format => 'm') %><span class="ctx-add"><%= link_to t('+'), new_todo_path(new_context_todo_params) %></span></h2>
<ul class="c">
<%= render :partial => "todos/todo",
           :collection => @not_done,
           :locals => { :parent_container_type => "context" }-%>
</ul>
<% end -%>

Downloads/tracks-2.3.0/app/views/contexts/_context_form.html.erb
<% context = context_form
-%>

<%= form_for(context, :html => {
    :id => dom_id(context, 'edit_form'),
    :class => "inline-form edit-context-form",
    :method => :put }) do
  -%>

  <div id="edit_error_status"><%= get_list_of_error_messages_for(context) %></div>

  <label for="context_name"><%= t 'contexts.context_name' %></label><br/>
  <%= text_field('context', 'name', :class => 'context-name', :tabindex => next_tab_index) %><br/>

  <label for="context_hide"><%= t 'contexts.context_state' %> </label><br/>
  <% ['active', 'hidden', 'closed'].each do | state | %>
    <%= radio_button(:context, 'state', state, {:tabindex => next_tab_index}) %> <%= state.titlecase %>
  <% end %>
  </br></br>

  <div class="submit_box">
    <div class="widgets">
      <button type="submit" class="positive" id="<%= dom_id(context, 'submit') %>" tabindex="<%=next_tab_index%>">
        <%=image_tag("accept.png", :alt => "") %>
        <%= t 'common.update' %>
      </button>
      <a href="" onclick="" class="negative">
        <%=image_tag("cancel.png", :alt => "") %>
        <%= t 'common.cancel' %>
      </a>
    </div>
  </div>
  <br/><br/>

<% end %>

Downloads/tracks-2.3.0/app/views/contexts/_context_listing.html.erb
<%
context = context_listing
suppress_drag_handle ||= false
suppress_edit_button ||= false
suppress_delete_button ||= false
%>
<div id="<%= dom_id(context, "container") %>" class="list">
  <div id="<%= dom_id(context) %>" class="context sortable_row" style="display:block">
    <%= suppress_delete_button ? "" : link_to_delete_context(context, image_tag( "blank.png", :title => t('contexts.delete_context'), :class=>"delete_item")) -%>
    <%= suppress_edit_button ? "" : link_to_edit_context(context, image_tag( "blank.png", :title => t('contexts.edit_context'), :class=>"edit_item")) -%>
    <%= suppress_drag_handle ? "" : image_tag('grip.png', :width => '7', :height => '16', :border => '0', :title => t('common.drag_handle'), :class => 'grip')-%>
    <div class="context_description">
      <%= link_to_context( context ) %> <%= raw " (#{count_undone_todos_phrase(context)})" %>
    </div>
  </div>
  <div id="<%= dom_id(context, 'edit') %>" class="edit-form" style="display:none;">
  </div>
</div>

Downloads/tracks-2.3.0/app/views/contexts/_context_listing.m.erb
<% context = context_listing -%>
<div id="ctx"><%= link_to context.name, context_path(context, :format => 'm') %><%= " (#{count_undone_todos_phrase(context)})".html_safe %></div>

Downloads/tracks-2.3.0/app/views/contexts/_new_context_form.html.erb
<%- reset_tab_index %>
<div id="context_new_container">

  <div id="toggle_context_link" class="hide_form">
    <a id="toggle_context_new" href="#" title="<%= t('contexts.hide_form_title') %>" accesskey="n"><%= t('contexts.hide_form') %></a>
  </div>

  <div id="context_new" class="context_new" style="display:block">
    <%= form_for(@new_context, :html => {:id => 'context-form',:name=>'context',:class => "inline-form", :method => :post }) do -%>

      <div id="error_status">
        <% if @new_context.errors.any? -%>
          <ul>
            <% @new_context.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        <% end -%>
      </div>

      <label for="context_name"><%= t 'contexts.context_name' %></label><br />
      <%= text_field( "context", "name", :tabindex => next_tab_index ) %><br />

      <label for="context_hide"><%= t 'contexts.context_hide' %></label>
      <%= check_box( "context_state", "hide", {:tabindex => next_tab_index} ) %><br />

      <div class="submit_box">
        <div class="widgets">
          <button type="submit" class="positive" id="context_new_submit">
            <%= image_tag("accept.png", :alt => "") + t('shared.add_context') %>
          </button>
        </div>
      </div>
      <br/><br/>
    <% end -%>
  </div>
</div>

Downloads/tracks-2.3.0/app/views/contexts/create.js.erb
<% if @saved -%>
  hide_empty_message();
  TracksPages.hide_errors();
  TracksPages.set_page_badge(<%= @down_count %>);
  add_context("<%=@context.state%>");
  clear_form();
<% else -%>
  TracksPages.show_errors(html_for_error_messages());
<% end -%>

function hide_empty_message() {
  $('div#<%=@context.state%>-contexts-empty-nd').hide();
}

function add_context(state) {
  $('#list-contexts-'+state).append(html_for_context_listing());
}

function clear_form() {
  $('#context-form').clearForm();
  $('#context-form input:text:first').focus();
}

function html_for_context_listing() {
  return "<%= @saved ? js_render('context_listing', {}, @context) : "" %>";
}

function html_for_error_messages() {
  return "<%= js_error_messages_for(@context) %>";
}

Downloads/tracks-2.3.0/app/views/contexts/destroy.js.erb
remove_deleted_context();

ContextListPage.update_all_states_count(<%=@active_contexts_count%>, <%=@hidden_contexts_count%>, <%=@closed_contexts_count%>)

TracksPages.set_page_badge(<%=@down_count%>);
TracksPages.page_inform("<%=  t('contexts.context_deleted', :name=>@context.name)%>");

/* TODO: refactor and move function to application.js */
function remove_deleted_context() {
  $('div#<%=dom_id(@context, "container")%>').slideUp(1000, function() {
      $('div#<%=dom_id(@context, "container")%>').remove();
  });
}

Downloads/tracks-2.3.0/app/views/contexts/edit.js.erb
<%- object_name = unique_object_name_for("edit_context_#{@context.id}") %>

var <%=object_name%> = {
  animate: function() {
    <%=object_name%>.replace_context_with_edit_form();
  },
  replace_context_with_edit_form: function() {
    $('div#<%=dom_id(@context)%>').fadeOut(250, function() {
      <%=object_name%>.show_edit_form();
      <%=object_name%>.set_focus();
    });
  },
  show_edit_form: function() {
    $('div#<%=dom_id(@context, 'edit')%>').html(<%=object_name%>.html_for_edit_form());
    $('div#<%=dom_id(@context, 'edit')%>').fadeIn(500);
  },
  set_focus: function() {
    $('input.context-name').focus();
  },
  html_for_edit_form: function() {
    return "<%= js_render('context_form', {}, @context) %>";
  }
};

<%= object_name %>.animate();

Downloads/tracks-2.3.0/app/views/contexts/index.m.erb
<h2><%= t('contexts.visible_contexts') %></h2><%= render :partial => 'context_listing', :collection => @active_contexts %>
<h2><%= t('contexts.hidden_contexts') %></h2><%= render :partial => 'context_listing', :collection => @hidden_contexts %>

Downloads/tracks-2.3.0/app/views/contexts/index.text.erb
<% @all_contexts.each do |c| -%>

<%= c.name.upcase %>
<%= count_undone_todos_phrase_text(c)%>. <%= c.hidden? ? t('contexts.status_hidden') : t('contexts.status_active') %>.
<% end -%>

Downloads/tracks-2.3.0/app/views/contexts/show.html.erb
<%
  suffix_completed = t('contexts.last_completed_in_context', :number=>prefs.show_number_completed)
  deferred_pending_options = {:append_descriptor => nil, :parent_container_type => 'context'}
  done_todo_options = {:append_descriptor => suffix_completed, :suppress_context => true, :parent_container_type => 'context'}
  show_empty_containers = (@group_view_by == 'context')
-%>
<div id="display_box">

  <%= empty_message_holder("not_done_context", @not_done_todos.empty?) %>

  <%= show_grouped_todos({:collapsible => false, :show_empty_containers => false, :parent_container_type => 'context'}) %>

  <% if @group_view_by == 'project' -%>
    <%= show_todos_without_project(@todos_without_project, {:collapsible => false, :parent_container_type => 'context', :title_param => @context.name}) -%>
  <% end -%>

  <%= show_deferred_pending_todos(@deferred_todos, @pending_todos, deferred_pending_options) %>

  <%= show_done_todos(@done, done_todo_options) unless @done.nil? %>
</div>

<div id="input_box">
  <%= render :partial => "shared/add_new_item_form" %>
  <%= render :file => "sidebar/sidebar" %>
</div>

Downloads/tracks-2.3.0/app/views/contexts/show.m.erb
<h2><%=@context.name%></h2>
<%
# select actions from this context
@not_done = @not_done_todos.select {|t| t.context_id == @context.id }

if not @not_done.empty?
  # only show a context when there are actions in it
-%>
<ul class="c">
<%= render :partial => @not_done, :locals => { :parent_container_type => "context" }-%>
</ul>
<% end -%>

Downloads/tracks-2.3.0/app/views/contexts/update.js.erb
<%-
  object_name = unique_object_name_for("update_context_#{@context.id}")
-%>
var <%=object_name%> = {
  <% unless @saved -%>
    animate: function() {
      TracksPages.show_edit_errors(<%=object_name%>.html_for_error_messages());
    },
    html_for_error_messages: function() {
      return "<%= js_error_messages_for(@context) %>";
    }
  <% else -%>
    animate: function() {
      TracksPages.page_inform('<%= t('contexts.save_status_message') %>');
      <% if @state_changed -%>
        <%=object_name%>.remove_and_re_add_context();
        <%=object_name%>.update_container_states();
      <% else -%>
        <%=object_name%>.replace_context_form_with_updated_context();
      <% end -%>
    },
    remove_and_re_add_context: function() {
      $('#<%=dom_id(@context, 'container')%>').slideUp(500, function() {
        $('#<%=dom_id(@context, 'container')%>').remove();
        $('#list-contexts-<%=@new_state%>').append(<%=object_name%>.html_for_context_listing());
      });
    },
    replace_context_form_with_updated_context: function() {
      $('#<%=dom_id(@context, 'container')%>').fadeOut(250, function() {
      <%
        # first add the updated context after the old one, then remove old one
        # using html() does not work, because it will replace the _content_ of
        # the container instead of the container itself, i.e. you will get
        # a container within a container which will break drag-and-drop sorting
      -%>
        $('#<%=dom_id(@context, 'container')%>').after(<%=object_name%>.html_for_context_listing());
        $('#<%=dom_id(@context, 'container')%>').remove();
        $('#<%=dom_id(@context, 'container')%>').fadeIn(500);
      });
    },
    update_container_states: function() {
      ContextListPage.update_all_states_count(<%=@active_contexts.count%>, <%=@hidden_contexts.count%>, <%=@closed_contexts.count%>);
    },
    html_for_context_listing: function() {
      return "<%= js_render('context_listing', {}, @context)%>";
    }
  <% end -%>
}

<%=object_name%>.animate();